name: Feature request
description: Suggest an idea for Termix
title: "[FEATURE]"
labels: [enhancement]
assignees: []
body:
  - type: input
    id: title
    attributes:
      label: Title
      description: Brief, descriptive title for the feature request
      placeholder: "Brief description of the feature"
    validations:
      required: true
  - type: textarea
    id: related-issue
    attributes:
      label: Is it related to an issue?
      description: Describe the problem this feature would solve
      placeholder: "Describe what problem this feature would solve..."
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: The Solution
      description: Describe your proposed solution in detail
      placeholder: "Describe how you envision this feature working..."
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context or screenshots about the feature request
      placeholder: "Add any other context about the feature request here..."
